First sprint
MaxiTrue/java-filmorate pull request #2
Opened 2022-04-24 16:37 UTC by MaxiTrue

2022-04-24 20:03 UTC, MaxiTrue commented
Созданы классы модели и контроллеры, а так же класс исключения

2022-04-25 03:41 UTC, eugene-lenkevich requested changes
Привет,  Максим, спасибо за PR

В целом все супер :)
Есть совсем небольшие замечания, посмотри комментарии ниже, пожалуйста

2022-04-25 03:41 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/exception/ValidationException.java
> +public class ValidationException extends RuntimeException {
Пусть все же тут будет проверяемое исключение, пользователь ввел неверные данные - вполне себе штатная ситуация :)

extends Exception

2022-04-25 03:41 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final Map<Long, Film> films = new HashMap<>();
Тут, кстати, можно использовать CuncurrentHashMap. Web - конкурентная среда по определению. fyi

https://habr.com/ru/post/132884/

2022-04-25 16:44 UTC, MaxiTrue commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final Map<Long, Film> films = new HashMap<>();
Исправил на Exception, уже на автомате RuntimeException использую). Заменил на ConcurrentHashMap

2022-04-25 17:32 UTC, eugene-lenkevich approved these changes
Все супер, само приложение, валидация ошибок :)

2022-04-25 18:49 UTC, merged