feat:
MaxiTrue/java-filmorate pull request #3
Opened 2022-05-10 14:26 UTC by MaxiTrue

1) Добавить новые контроллеры FriendController и LikeController
2) Создать классы сервисы FilmService и UserService, перенсти всю бизнес-логику приложения в них
3) Добавить один общий интерфейс для реализации хранилищ данных Storage, сделать два интерфеса под храненение пользователеф и фильмов, унаследоваться от основного, так задумано для более гибкой настройки хранилищ
4) Добавить отдельные прослойти для хранилищ в виде двух классов InMemoryFilmStorage и InMemoryUserStorage они должны наследовать каждый свой интерфейс
5) Добавить сущность ErrorResponse, будем её использовать для возврата в обработчике исключений
6) Добавить исключения FilmNotFoundException, UserNotFoundException, IncorrectParameterException
7) Добавить общий обработчик для исключений ErrorHandler

2022-05-10 16:40 UTC, eugene-lenkevich requested changes
Привет,  Максим, спасибо за PR

В целом все супер :)
Есть совсем небольшие замечания, посмотри комментарии ниже, пожалуйста

2022-05-10 16:40 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/LikeController.java
> +    public LikeController(FilmService filmService) {
Если зависимости объявить вот так

private final FilmService filmService;

и добавить аннотацию контролеру @RequiredArgsConstructor, то конструтор можно не описывать, lombok его сгенерирует автоматически :)

2022-05-10 16:40 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/exception/FilmNotFoundException.java
> +public class FilmNotFoundException extends RuntimeException {
RuntimeException - непроверяемое(unchecked) исключение, оно означает что в логике произошла нештатная ситуация и состояние стало неконсистентным (так же как и NullPointerException, например).
Однако, отсутствие сущности - штатная, предсказуемая, ситуация. Здесь стоит кидать проверяемое (checked) исключение, throw new Exception(...) (ну и обработать его выше по стеку, на то оно и проверяемое =)

2022-05-10 16:40 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/exception/IncorrectParameterException.java
> +public class IncorrectParameterException extends RuntimeException {
extends Exception, аналогично

2022-05-10 16:40 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (film.getName() == null ||
Тут можно использовать 
StringUtils.hasText
или же аналогичную функцию из apache commons 
StringUtils.isNotBlank
=)

2022-05-10 16:40 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (film.getDescription().isBlank() || film.getDescription().length() > 200) {
film.getDescription().trim().length() ...
Так, думаю, покороче :)

2022-05-10 16:40 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        return films.get(id);
А почему бы не возвращать просто null  в случае если объект не найден, выкидывать исключение - не слишком ли сурово? но не настаиваю

2022-05-10 18:18 UTC, MaxiTrue commented
Что касается броска исключения , а не возврата null, сделал так чисто для подгона тестов постман, там есть тест, приложу скрин, он ожидает ответ 404, при попытки найти фильм с id - (-1), а в ТЗ сказано что 404 ошибку кидать когда не нашли, все скрины приложил. 
![image](https://user-images.githubusercontent.com/96014701/167695495-64b23eb0-79c6-4ff9-8d29-2786655d5f1e.png)
![image](https://user-images.githubusercontent.com/96014701/167695779-8115b851-1133-4ba6-a6d9-d122553db5c3.png)
![image](https://user-images.githubusercontent.com/96014701/167695868-ef0a0888-bab3-4d99-bede-dcfa9aa56a87.png)

2022-05-11 03:14 UTC, eugene-lenkevich commented
> Что касается броска исключения 
В целом возвращаемый код можно задавать в контроллере, 500, 201 и пр ;)
Исключения чреваты тем, что проверяемые не выкидываются в стримах, а кидать непроверяемые не очень с архитектурной точки зрения. Но ладно :)

2022-05-11 03:16 UTC, eugene-lenkevich approved these changes
Все супер, спасибо!

2022-05-13 18:10 UTC, merged