refactor: Изменить схему БД, заменить файл database_filmorate.png(был…
MaxiTrue/java-filmorate pull request #5
Opened 2022-06-26 22:16 UTC by MaxiTrue

…и внесены сильные изменения)

fix: Перенести всю реализацию работы с хранилищами из классов сервисов в классы хранилища
refactor: Вместо нескольких классов исключений типа NotFound на каждую сущность, заменить на единый универсальный класс ObjectNotFoundException
feat: Создать файлы по построению БД schema.sql и data.sql
feat: Реализовать под каждую таблицу БД класс DAO
feat: Добавить классы тесты под классов DAO

2022-06-27 07:39 UTC, eugene-lenkevich requested changes
Привет, Максим, спасибо за PR

В целом все супер :)
Но хотелось бы поправить несколько семантических моментов, посмотри комментарии ниже, пожалуйста

2022-06-27 07:39 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/dao/GenreDao.java
> +    public Collection<Genre> findAllGenre() {
А не будет ли тут у нас тавтологии :)
Бин называется GenreDao, он, по определению, работает с объектами Genre, но в именах методой мы это повторяем второй раз.

2022-06-27 07:39 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/dao/GenreDao.java
> +    protected void deleteGenreForFilm(Long filmId) {
Вообще, методы лучше называть в едином ключе (я насчитал три варианта названий =), это заметно снижает когнитивную нагрузку.
Кажется что вот так будет понятней
deleteByFilmId

2022-06-27 07:39 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public Collection<User> findAllUser() {
Множественное ж число :)
findAllUsers
или просто
findAll

2022-06-27 07:39 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        User user = storageUsers.findById(userId);
Похоже тут у нас неиспользуемая переменная и ненужный вызов метода :)

2022-06-27 07:39 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        User user = storageUsers.findById(userId);
Опять таки, снова непонятные вызовы, предположу, что тут проверяется существование объектов в БД, но тогда семантически это стоит оформить так, чтобы стороннему наблюдателю было понятно что же тут происходит :)

2022-06-27 07:56 UTC, MaxiTrue commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        User user = storageUsers.findById(userId);
Евгений, привет). Да, я так проверяю наличие объекта. а как это делать правильно и канонично? Есть идея только из слоя хранилища, отдавать объект Optional, если нашёл , обворачиваем в Optional, если нет возвращаем Optional.isEmpty()

2022-06-27 19:22 UTC, MaxiTrue commented on src/main/java/ru/yandex/practicum/filmorate/dao/GenreDao.java
> +    protected void deleteGenreForFilm(Long filmId) {
Исправлено

2022-06-27 19:24 UTC, MaxiTrue commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public Collection<User> findAllUser() {
Исправлено

2022-06-27 19:24 UTC, MaxiTrue commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        User user = storageUsers.findById(userId);
Исправлено

2022-06-28 08:12 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        User user = storageUsers.findById(userId);
> Евгений, привет). Да, я так проверяю наличие объекта. а как это делать правильно и канонично? Есть идея только из слоя хранилища, отдавать объект Optional, если нашёл , обворачиваем в Optional, если нет возвращаем Optional.isEmpty()

Да, это очень даже рабочее решение, часто именно так и делают :)

Тут еще был и несколько другой вопрос - не понятно что код делает, со стороны выглядит как будь-то лишний вызов метода, можно было сделать спец-метод что-то типа isExists :)

2022-06-28 08:15 UTC, eugene-lenkevich approved these changes
Все супер, спасибо!

2022-06-28 08:20 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        User user = storageUsers.findById(userId);
В целом сейчас норм, гораздо понятнее стало, вообще с Optional гораздо проще в том плане что можно писать код в, так скажем, функциональном стиле, то есть без явных if-else, вот примерно как так так (главное не увлекаться иначе можно читаемость сильно усложнить =)

![image](https://user-images.githubusercontent.com/94845100/176130287-5c0ceb0b-92c6-444c-b1e2-4c0f91529332.png)

2022-06-28 09:33 UTC, merged